name = "ATRSim"
uuid = "b475fd22-282a-48c5-9344-a81478fb2b0f"
authors = ["stakahama <satoshi.takahama@gmail.com> and contributors"]
version = "1.0.0-DEV"

[deps]
Integrals = "de52edbc-65ea-441a-8357-d3a637375a31"

[compat]
Integrals = "4.5.0"
julia = "1.6.7"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
